# Generated by Django 4.1.3 on 2022-11-21 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='curso',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='curso',
            new_name='nombre',
        ),
    ]
